# fly.toml file generated for dd-agent on 2022-05-05T11:33:31-07:00

app = "dd-agent"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8126"
  DD_SITE = "datadoghq.com"
  DD_APM_NON_LOCAL_TRAFFIC = true

[build]
  image = "datadog/agent:7"

[build.args]
  DD_AGENT_ARTIFACT = "./datadog-agent_7-1_amd64.deb"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8126
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8126

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "10s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
