apiVersion: skaffold/v2beta2
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: kots-lint
      docker:
        dockerfile: skaffold.Dockerfile

deploy:
  kustomize:
    paths:
      - "./kustomize/overlays/skaffold"