apiVersion: v1
kind: Service
metadata:
  name: kots-lint
  labels:
    app: kots-lint
spec:
  type: NodePort
  ports:
  - name: kots-lint
    port: 8082
    targetPort: kots-lint
    nodePort: 30082
  selector:
    app: kots-lint