apiVersion: v1
kind: Service
metadata:
  name: kots-lint
  labels:
    app: kots-lint
  annotations:
    dev.okteto.com/auto-ingress: "true"       
spec:
  type: ClusterIP
  ports:
  - name: kots-lint
    port: 8082
    targetPort: kots-lint
  selector:
    app: kots-lint