apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
  labels:
    app: example
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      labels:
        app: example
        component: nginx
    spec:
      containers:
        - image: nginx
          envFrom:
          - configMapRe:
              name: example-config
          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'