on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"

jobs:
  build-kots-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.8"

      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash

      - uses: actions/checkout@v2

      - run: make test build

  goreleaser:
    runs-on: ubuntu-latest
    needs: build-kots-lint
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.8"

      - run: sudo apt-get -qq -y install 

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --config deploy/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}